- 
  name: 1 small fan
  pin: 5
  inverted: true
  events:
    - start: 8000
      end: 1100
    - start: 1230
      end: 1600
    - start: 1630
      end: 2230
- 
  name: 2 big fan
  pin: 6
  events:
    - start: 8000
      end: 1100
    - start: 1230
      end: 1600
    - start: 1630
      end: 2230
- 
  name: 3 fluval pump
  pin: 13
  events:
    - start: 0001
      end: 1300
    - start: 1305
      end: 2359
- 
  name: 4 blue pump
  pin: 19
  events:
    - start: 0002
      end: 1100
    - start: 1102
      end: 1600
    - start: 1602
      end: 1900
    - start: 1902
      end: 2359
- 
  name: switch 5 co2
  pin: 26
  events:
    - start: 1400
      end: 1600
    - start: 1605
      end: 1800
    - start: 1805
      end: 1930
- 
  name: switch 6 heater
  pin: 20
  events:
    - start: 0002
      end: 1100
    - start: 1102
      end: 1600
    - start: 1602
      end: 1900
    - start: 1902
      end: 2359
