- 
  name: 1 small fan
  pin: 5
  inverted: true
  events:
    - start: 0800
      end: 1100
    - start: 1230
      end: 1600
    - start: 1630
      end: 2230
- 
  name: 2 big fan
  pin: 6
  events:
    - start: 0800
      end: 1100
    - start: 1230
      end: 1600
    - start: 1630
      end: 2230
- 
  name: 3 heater
  pin: 13
  events:
    - start: 0001
      end: 2359
- 
  name: 4 pumps
  pin: 19
  events:
    - start: 0001
      end: 1100
    - start: 1101
      end: 1600
    - start: 1601
      end: 1900
    - start: 1901
      end: 2359
- 
  name: 5 co2
  pin: 26
  events:
    - start: 1100
      end: 1558
    - start: 1605
      end: 1800
    - start: 1805
      end: 2014
- 
  name: 6 extra
  pin: 20
  events:
    - start: 0001
      end: 0002
