- 
  name: filter
  pin: 5
  inverted: true
  events:
          - start: 0000
            end: 0010
          - start: 0800
            end: 0801
          - start: 0900
            end: 0901
          - start: 2100
            end: 2120
- 
  name: co2
  pin: 6
  events:
    - start: 1200
      end: 1600
- 
  name: switch 3 small fan
  pin: 13
  events:
          - start: 1030
            end: 1300
          - start: 1530
            end: 2230
- 
  name: switch 4 big fan
  pin: 19
  events:
          - start: 8000
            end: 1100
          - start: 1230
            end: 1600
          - start: 1630
            end: 2230
- 
  name: switch 5
  pin: 26
- 
  name: switch 6
  pin: 20
  events:
    - start: 0000
      end: 0100
